<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace AlibabaCloud\Dkms\Gcs\OpenApi\Util\Protobuf\GPBMetadata;

class Api
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ê!
	api.protoapi"s
EncryptRequest
KeyId (	
	Plaintext (
	Algorithm (	
Aad (

Iv (
PaddingMode (	"
EncryptResponse
KeyId (	
CiphertextBlob (

Iv (
	RequestId (	
	Algorithm (	
PaddingMode (	"x
DecryptRequest
CiphertextBlob (
KeyId (	
	Algorithm (	
Aad (

Iv (
PaddingMode (	"n
DecryptResponse
KeyId (	
	Plaintext (
	RequestId (	
	Algorithm (	
PaddingMode (	"e
SignRequest
KeyId (	
Digest (
	Algorithm (	
Message (
MessageType (	"k
SignResponse
KeyId (	
	Signature (
	RequestId (	
	Algorithm (	
MessageType (	"z
VerifyRequest
KeyId (	
Digest (
	Signature (
	Algorithm (	
Message (
MessageType (	"i
VerifyResponse
KeyId (	
Value (
	RequestId (	
	Algorithm (	
MessageType (	"-
HmacRequest
KeyId (	
Message ("C
HmacResponse
KeyId (	
	Signature (
	RequestId (	"\'
GenerateRandomRequest
Length (";
GenerateRandomResponse
Random (
	RequestId (	"^
GenerateDataKeyRequest
KeyId (	
	Algorithm (	
NumberOfBytes (
Aad ("Ö
GenerateDataKeyResponse
KeyId (	

Iv (
	Plaintext (
CiphertextBlob (
	RequestId (	
	Algorithm (	"$
GetPublicKeyRequest
KeyId (	"K
GetPublicKeyResponse
KeyId (	
	PublicKey (	
	RequestId (	"W
Error

StatusCode (
	ErrorCode (	
ErrorMessage (	
	RequestId (	"q
GetSecretValueRequest

SecretName (	
VersionStage (	
	VersionId (	
FetchExtendedConfig ("æ
GetSecretValueResponse

SecretName (	

SecretType (	

SecretData (	
SecretDataType (	
VersionStages (	
	VersionId (	

CreateTime (	
	RequestId (	
LastRotationDate	 (	
NextRotationDate
 (	
ExtendedConfig (	
AutomaticRotation (	
RotationInterval (	"z
AdvanceEncryptRequest
KeyId (	
	Plaintext (
	Algorithm (	
Aad (

Iv (
PaddingMode (	"ú
AdvanceEncryptResponse
KeyId (	
CiphertextBlob (

Iv (
	RequestId (	
	Algorithm (	
PaddingMode (	
KeyVersionId (	"
AdvanceDecryptRequest
CiphertextBlob (
KeyId (	
	Algorithm (	
Aad (

Iv (
PaddingMode (	"ã
AdvanceDecryptResponse
KeyId (	
	Plaintext (
	RequestId (	
	Algorithm (	
PaddingMode (	
KeyVersionId (	"R
AdvanceGenerateDataKeyRequest
KeyId (	
NumberOfBytes (
Aad ("¢
AdvanceGenerateDataKeyResponse
KeyId (	

Iv (
	Plaintext (
CiphertextBlob (
	RequestId (	
	Algorithm (	
KeyVersionId (	"s
GenerateDataKeyPairRequest
KeyId (	
	Algorithm (	
KeyPairSpec (	
	KeyFormat (	
Aad ("≈
GenerateDataKeyPairResponse
KeyId (	

Iv (
KeyPairSpec (	
PrivateKeyPlaintext ( 
PrivateKeyCiphertextBlob (
	PublicKey (
	RequestId (	
	Algorithm (	"É
*GenerateDataKeyPairWithoutPlaintextRequest
KeyId (	
	Algorithm (	
KeyPairSpec (	
	KeyFormat (	
Aad ("∏
+GenerateDataKeyPairWithoutPlaintextResponse
KeyId (	

Iv (
KeyPairSpec (	 
PrivateKeyCiphertextBlob (
	PublicKey (
	RequestId (	
	Algorithm (	"g
!AdvanceGenerateDataKeyPairRequest
KeyId (	
KeyPairSpec (	
	KeyFormat (	
Aad ("‚
"AdvanceGenerateDataKeyPairResponse
KeyId (	

Iv (
KeyPairSpec (	
PrivateKeyPlaintext ( 
PrivateKeyCiphertextBlob (
	PublicKey (
	RequestId (	
	Algorithm (	
KeyVersionId	 (	"w
1AdvanceGenerateDataKeyPairWithoutPlaintextRequest
KeyId (	
KeyPairSpec (	
	KeyFormat (	
Aad ("’
2AdvanceGenerateDataKeyPairWithoutPlaintextResponse
KeyId (	

Iv (
KeyPairSpec (	 
PrivateKeyCiphertextBlob (
	PublicKey (
	RequestId (	
	Algorithm (	
KeyVersionId (	BÆ
)com.aliyun.dkms.gcs.openapi.util.protobufB	ApiModelsZ./protobuf/api +AlibabaCloud\\Dkms\\Gcs\\OpenApi\\Util\\Protobuf‚7AlibabaCloud\\Dkms\\Gcs\\OpenApi\\Util\\Protobuf\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

